name: CI to GitHub Packages
on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    name: Build semenovp/tiny-uglify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup BuildX to use Docker Driver.
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            vcsref=${GITHUB_SHA::8}
          tags: semenovp/tiny-uglify:latest

      - name: Push to Registry
        run: |
          docker tag semenovp/tiny-uglify:latest docker.pkg.github.com/piotr-semenov/semenovp/tiny-uglify:latest
          docker images
          docker push docker.pkg.github.com/piotr-semenov/semenovp/tiny-uglify:latest
