name: CI to GitHub Packages
on:
  push:
    branches: [main]

env:
  IMAGE_TAG: tiny-uglify:latest
  REGISTRY: docker.pkg.github.com

jobs:
  build_and_publish:
    name: Build tiny-uglify:latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup BuildX to use Docker Driver.
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            vcsref=${GITHUB_SHA::8}
          tags: ${{ env.IMAGE_TAG }}

      - name: Push to Registry
        run: |
          docker tag ${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${GITHUB_REPOSITORY}/${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${GITHUB_REPOSITORY}/${{ env.IMAGE_TAG }}
