name: CI to GitHub Packages
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build semenovp/tiny-uglify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            vcsref=${GITHUB_SHA::8}
          repository: semenovp/tiny-uglify
          tags: latest
